### PR TITLE
Fix i18n directory not resolving properly when parentheses are used

### LINKED ISSUE #66: i18n util fails if projects are run from a path with spaces in it
**Describe the bug**
After having followed the setup instructions, I'm trying to run ´npm run dev´ but it fails with this error: 

```
site/_js/main.js, site/_js/100.js, site/_js/events.js, site/_js/styleguide.js, site/_js/fugu-showcase.js → dist/js...
created dist/js in 217ms

> developer.chrome.com@1.0.0 eleventy
> eleventy

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] No translations for: i18n.authors.timstatler.title (via Error)
[11ty]
[11ty] Original error stack trace: Error: No translations for: i18n.authors.timstatler.title
[11ty]     at I18nDictionary.get (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/webdev-infra/utils/i18nDictionary.js:84:13)
[11ty]     at I18nFilter.filter (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/webdev-infra/filters/i18n.js:52:29)
[11ty]     at /Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/site/en/authors/authors.11tydata.js:24:9
[11ty]     at Array.sort (<anonymous>)
[11ty]     at Object.before (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/site/en/authors/authors.11tydata.js:23:22)
[11ty]     at Pagination._resolveItems (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:175:37)
[11ty]     at Pagination.setData (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:96:26)
[11ty]     at new Pagination (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:19:10)
[11ty]     at Template.getTemplates (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/@11ty/eleventy/src/Template.js:724:21)
[11ty]     at TemplateMap.initDependencyMap (/Users/obfuscatedusername/Dropbox (Personal)/projects/developer_chrome_com/developer.chrome.com/node_modules/@11ty/eleventy/src/TemplateMap.js:288:41)
[11ty] Wrote 0 files in 2.14 seconds (v1.0.2)
ERROR: "eleventy" exited with 1.
```
**To Reproduce**
clone the repo, run `npm ci` and then run `npm run dev`, error appears.

**Expected behavior**
Site should build for dev.

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 (22D68)
 - Browser: Chrome Version 111.0.5563.64 (Official Build) (arm64)
- Node: tried v14.21.3 (npm v6.14.18) and v18.15.0

**Additional context**
Is there perhaps some step missing in the setup instructions?

### PR DESCRIPTION
**Pull request by ShayPunter**
Fixes #66

It would appear that the issue does not relate to the use of spaces, but rather special characters. This also seems to only effect parentheses, and no other special characters as tested (tested with the following: <> [] {} -- == ** ^^).

## How to test
1. Clone webdev-infra and checkout this branch '77_i18n_util_fails_if_run_from_path_with_spaces'
2. Create a local folder which contains parentheses in (e.g. /Shay/programming/Shay (test)/)
3. Clone developer.chrome.com or web.dev to the folder
4. Setup a symlink to the appropriate place
5. run 'npm ci'
6. run 'npm run dev'
7. successful build should happen

### CODE REVIEW

File: utils/i18nDictionary.js [hunk 1]
```diff
@@ -52,7 +52,9 @@ class I18nDictionary {
    * @param {string} dir The directory to walk
    */
   loadEntries(dir) {
-    const files = fg.sync(path.join(dir, '/**/*.{yml,yaml}'));
+    const files = fg.sync(path.join(dir.replace(/([()])/g, '\\$1'), '/**/*.{yml,yaml}'));
+
+    console.log(files)
```
Comment (simgobb) [inline utils/i18nDictionary.js:57]: Leftover log

File: utils/i18nDictionary.js [hunk 2]
```diff
@@ -52,7 +52,7 @@ class I18nDictionary {
    * @param {string} dir The directory to walk
    */
   loadEntries(dir) {
-    const files = fg.sync(path.join(dir, '/**/*.{yml,yaml}'));
+    const files = fg.sync(path.join(dir.replace(/([()])/g, '\\$1'), '/**/*.{yml,yaml}'));
```
Comment (matthiasrohmer) [inline utils/i18nDictionary.js:55]: Please move the regular expression to a well named const at the top of the file with its name ending in `PATTERN` and then use here. Also do the tidiying in a new variable, like `const cleanDir = dir.replace(...` and add a comment what is replaced and why.

**Review by matthiasrohmer — COMMENTED** [review]
Thanks, just a style comment!

**Review by matthiasrohmer — APPROVED** [review]
